version: '2.3'

services:
  docker:
    container_name: docker
    image: docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_slave_docker_workdir:/home/jenkins:z
    privileged: true
volumes:
  jenkins_slave_docker_workdir:
  jenkins-docker-certs:

